### ISSUE TITLE
Cannot activate this extension

### ISSUE THREAD

**Issue by Ben136KBC** [stef-levesque/vscode-perforce#100]
I had this extension working very nicely! Awesome extension, thank you. But after a recent update, it stopped working. I have removed it, uninstalled it, you name it.

So with it uninstalled, I go to the SCM page, and click the More button. It only gives me the option to install more SCM providers. I click that. It shows me several available extensions, including the vscode-perforce one. I click Install.  I click Reload. Now if I go to the SCM page and click the More button,  it again ONLY shows me the option to install additional SCM providers. And the list it gives me when I do that, again shows vscode/perforce, but shows it as being installed. It shows that it is up to date, as is my vscode.  If I click on its settings buttons, it seems to be enabled, as it only shows options to disable it.

I restart vscode, and go to the SCM page, and it says "There are no source controls active". If I go to the list of installed extensions, it shows vscode-perforce as isntalled and enabled. Nothing in the log or problems tab.

What gives? It seems to be installed, yet vscode acts as if it is not.

It was working fine on the folder in question, the same folder I have now, and I have not changed any settings since then.

Using vscode 1.16.1, 64 bit. on Windows.
Attempting to use version 2.2.1 of the extension.

Please help! Is there some sort of log file or troubleshooting guide to tell you why this extension is not working?

**Comment by stef-levesque** [comment]
We are reworking the way the extension will activate, in order to support multiple workspaces.

Can you try to set the following in your global settings, reload your workspace, and see if you can activate the Perforce Log in the command palette ?

`"perforce.activationMode": "always"`

**Comment by Ben136KBC** [comment]
Hi, with that option added, your extension seems to load and work now. The Perforce log shows a bunch of p4.exe commands. Thanks. BTW: I did have a folder open, the same one that automatically reopens when I start vscode.

**Comment by stef-levesque** [comment]
How is your p4 settings configured? Are you using global settings pointing to a default depot? Are you using env vars or .p4config files?

**Comment by Ben136KBC** [comment]
In the folder I opened, I have a .p4config file containing:
P4CLIENT=MCH3_Client3
(This is because the plugin picks the wrong client otherwise, the machine has many clients)
In my User settings I have:
    "perforce.activationMode": "always"    
There are no P4 relevant environment variables. It must be getting the rest of the settings from wherever P4V saves them.
I do not set P4CLIENT in the vscode user settings or environment, as there are may clients, and the right one depends on the folder. So it is convenient that a .P4CONFIG file in the work folder seems to work now.
Anything else I can do to help or test please let me know.
Thanks.

**Comment by stef-levesque** [comment]
Ok, the problem may come from the fact that you have multiple `.p4config` files in the same workspace, even if they are in different sub-folders.

I'll investigate why it break the `autodetect` mode. Thanks for the info!

**Comment by Ben136KBC** [comment]
Nope, there is one and only one .P4CONFIG file in the workspace directory. and none in any sub directories.  The other client directories are elsewhere on the machine.

**Comment by stef-levesque** [comment]
Hm, it's curious then...
If there is no sensitive information, could you copy in the output of 
`Perforce: Display client/server information`

And maybe also, run `p4.exe set` from VSCode Terminal?

**Comment by Ben136KBC** [comment]
The funny thing is, now that I have .the .P4CONFIG and it has loaded, I can remove the perforce.activationMode from my workspace and user settings, and the extension still loads and works fine. (When it was not working I did not have a .P4CONFIG but rather set the client in the user preference settings). If I remove the .P4CONFIG file, then it reverts back to "There are no source controls active". If I bring it back, it starts to work again. If I remove the .P4CONFIG file and set the client in the workspace preference settings instead, then the extension stops working again.

So I am guessing the extension works if it can find valid settings, which may require a .P4CONFIG file. The settings in the workspace preference (perforce.client) does not seem to work anymore. But that is fine for me.

The client server information is (edited some names slightly to remove confidential info):
p4.exe -c BXXXXXXX_Client3 -d e:/Perforce/Client3/main/xxxx-sim/ info
User name: vxxxxxx
Client name: BXXXXXX_Client3
Client host: BXXXXX4
Client root: e:\Perforce\Client3
Current directory: e:/Perforce/Client3/main/xxxxx-sim/
Peer address: 10.37.18.8:62292
Client address: 10.37.20.30
Server address: Axxxxx1.xxxxx.com:1666
Server root: d:\Perforce
Server date: 2017/09/25 10:53:01 -0500 Central Daylight Time
Server uptime: 813:22:09
Server version: P4D/NTX64/2017.1/1545029 (2017/08/16)
Proxy address: Cxxxx1.xxxxx.com:1666
Proxy version: P4P/NTX64/2017.1/1545029 (2017/08/16)
Server license: xxxxxxx  xxx users (support ends 2018/09/13) 
Server license-ip: 10.37.3.60:1666
Case Handling: insensitive

From a command shell, p4.exe set reports:
P4EDITOR=xxxxxxx (Set)
P4PORT=Cxxxxx:16666 (set)
P4USER=vXXXXXX
P4_cxxxxxx:1666_CHARSET=none (set)

**Comment by Ben136KBC** [comment]
I am guessing that setting the perforce.client in the user settings, requires the activationMode always setting to work. But if you instead you set the client via .P4CLIENT, then the activationMode is not required.

**Comment by stef-levesque** [comment]
Ok, then PR #99 is likely to fix this issue. Just a few more test and I'll push a new version of the extension.

**Comment by Ben136KBC** [comment]
Yes, it is just a typo. BTW: Thank you for this extension it is awesome, I appreciate how much work it is! You are doing it just for the love of it?

**Comment by stef-levesque** [comment]
To be honest, maintaining the project is a bit more work than I initially thought.
But since some people are using it on a daily basis, it might just worth it :)

**Comment by Ben136KBC** [comment]
Sadly, if you exit vscode and wait some time before loading it, then the extension start using the wrong client, instead of the one set in .P4CONFIG. So I am back to having perforce.client in the user workspace settings.
