### ISSUE TITLE
p4config.txt doesn't seem to be used

### ISSUE THREAD

**Issue by anthony-brien** [stef-levesque/vscode-perforce#101]
In the root of all my workspaces, I have a p4config.txt file that contains which P4CLIENT and P4HOST is associated with each workspace. This makes the perforce extensions in Visual Studio automatically connect correctly. 

However, I cannot get this to work in VSCode with this extension.

If I add "perforce.port" and "perforce.client" to the workspace settings it works. But I'd prefer not to have to add this redundant information for each workspace.

**Comment by stef-levesque** [comment]
Yes, we are working on that.
In the meanwhile, can you try to copy your `p4config.txt` to `.p4config` ?

**Comment by anthony-brien** [comment]
I have the same issue if I move my p4config.txt to .p4config (and I updated the P4CONFIG environment variable to point to .p4onfig)..

**Comment by stef-levesque** [comment]
I pushed a new version of the extension (2.2.2) Let me know if it resolve your issue.

**Comment by anthony-brien** [comment]
Works like a charm! Thanks :)
