### ISSUE TITLE
Move to changelist via shortcut not working

### ISSUE THREAD

**Issue by kiwi1342** [stef-levesque/vscode-perforce#102]
Hi,

I've configured a shortcut to move the current file to a defined changelist but it doesn't work. It opens the menu to select a changelists but when I select one the file doesn't move.
I'm currently with version 2.2.1

thanks

**Comment by stef-levesque** [comment]
I pushed a new version of the extension (2.2.2) Is it still happening?

**Comment by stef-levesque** [comment]
Closing for now, please re-open if this is still an issue.
