### ISSUE TITLE
Revert file is not clearing the file on the source-control window

### ISSUE THREAD

**Issue by revanth98** [stef-levesque/vscode-perforce#112]
In user settings, "perforce.editOnFileSave": true is set

When we edit the file, it is displayed on the source control.
After, we revert the file, it still shows on the source control window.

Note: same behavior is not observed on my colleagues vscode

**Comment by stef-levesque** [comment]
A few questions:

- Do you use a multi-root workspace ?
- If you remove the `perforce.editOnFileSave` setting, is it still happening ?
- Try manually refresh the SCM, do you still see the file ?
- Run `Perforce: Show Output`, do you see an error after reverting ?
- Can you compare the output with one of your colleagues ?

**Comment by stef-levesque** [comment]
This is likely fixed with version 3.1.0
Please update and re-open if it is still happening.
