### ISSUE TITLE
not existing changelists are still shown regardless "Refresh"

### ISSUE THREAD

**Issue by easz** [stef-levesque/vscode-perforce#113]
At some point I have two changelist shown correctly in SCM pannel

changelist 1 
changelist 2

After I commit changelist 1 **outside** the vscode-perforce plugin 
it still show both changelists in SCM pannel even I "Refresh" it

from the log terminal:
the plugin does attempt only with
p4.exe .... describe -Ss 2

{I am not sure if there is any duplicate bug}

**Comment by stef-levesque** [comment]
This is likely fixed with version 3.1.0
Please update and re-open if it is still happening.
