### ISSUE TITLE
Option for Active Changelist and show only active changelist in VCS explorer

### ISSUE THREAD

**Issue by kalpeshhpatel** [stef-levesque/vscode-perforce#114]
Hey there, 

Thanks for this awesome plugin. I am just wondering if there is an option for setting default active change list (CL) in plugin, so that all my edited files goes to that CL by default and I don't have to manually move my edited files to desired CL.

It would be also nice, if in VCS explorer, I can filter out changes for active CL only.

The reason I am looking for this option is because, sometime in workspace of large projects, we do work with just subtree of large project structure, and sometimes we are interested in active chagelist only. 

Thanks for your times. 
Cheers :)

**Comment by kalpeshhpatel** [comment]
Can you please link duplicate issue here?

**Comment by stef-levesque** [comment]
Having a default changelist is being tracked in issue #22

As for only displaying that changelist, I think it would be confusing for some user to not see everything.

**Comment by stef-levesque** [comment]
If it is of any help, note that you can set `perforce.changelistOrder` to `ascending` or `descending` order, if you prefer your latest changelist to display at the top.

**Comment by stef-levesque** [comment]
Closing for now, please add your comments and suggestions in #22
