### ISSUE TITLE
Source control pane polluted with duplicate changelists

### ISSUE THREAD

**Issue by mzbik** [stef-levesque/vscode-perforce#115]
Started VS Code, start editing (source control pane hidden).  In another window, start a VS2017 build, come back to VS Code, open source control pane and get:

![image](https://user-images.githubusercontent.com/2048333/34061940-0a629840-e19f-11e7-834c-4a3e410b5e09.png)

Refresh doesn't clear them out.

Reloading window fixes it.

**Comment by stef-levesque** [comment]
Can you provide the Perforce logs when this happen ?
`Perforce: Show Output`

**Comment by stef-levesque** [comment]
Closing it as duplicate.
Please provide your Perforce logs, user settings, and what you where doing in issue #62
