### ISSUE TITLE
Diff of a large file fails with "Error: stdout maxBuffer exceeded"

### ISSUE THREAD

**Issue by madakk** [stef-levesque/vscode-perforce#116]
Apparently the call to `p4.exe print -q` fails. The file in question is 272kb.

Edit: To clarify this only happens when editing an open file via the changelist. If I manually diff a file it seems to call `p4.exe print -q -o` to a tmp file, which works fine.

**Comment by stef-levesque** [comment]
The default value for `perforce.maxBuffer` is `204800` (200KB)
You can increase it to your needs in your user profile. I personally set it to 1MB on large projects:
```json
{ 
  "perforce.maxBuffer": 1048576
}
```

I might increase the default value on the next release

**Comment by madakk** [comment]
Thanks for the response, that's perfect.

Perhaps a good thing to do would be to at least catch this error and report it to the user, as it seems to just hang there and do nothing and without examining the output log you'd have no clue that an error had happened.

**Comment by stef-levesque** [comment]
The error should display in the status bar, next to the p4 icon, for a few seconds, although it might not be that much noticeable.

It was previously displaying as a message box next to the command palette, but people found it annoying. I should probably priorities some error messages, and implement a mechanism to individually ignore them.
