### ISSUE TITLE
Error when using SSL server

### ISSUE THREAD

**Issue by tivac** [stef-levesque/vscode-perforce#118]
I have a `P4CONFIG=p4.ini` set, and a `p4.ini` file a few directories up from where I'm working.

It looks like this:

```ini
P4CLIENT=user_workspace
P4PORT=ssl:not.my.real.server.com:1666
P4PASSWD=NOTAREALPASSWORD
P4USER=user
```

But whenever the perforce extension tries to edit a file I get this error reported in the log.

```
ERROR: "Failed client connect, server using SSL.\r\nClient must add SSL protocol prefix to P4PORT.\r\n"
```

If I run `p4 set` from the vscode terminal I see what I'd expect for output.

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

F:\workspace\project\dev\>p4 set
P4CLIENT=user_workspace (config 'f:\workspace\p4.ini')
P4CONFIG=p4.ini (set) (config 'f:\workspace\p4.ini' )
P4EDITOR=C:\Program Files (x86)\Microsoft VS Code\Code.exe (set)
P4IGNORE=.p4ignore (set)
P4PASSWD=NOTAREALPAASWORD (config 'f:\workspace\p4.ini')
P4PORT=ssl:not.my.real.server.com:1666 (config 'f:\workspace\p4.ini')
P4USER=user (config 'f:\workspace\p4.ini')
P4_ssl:not.my.real.server.com:1666_CHARSET=none (set)
```

Is there a way to see the actual commands being run or anything else that might help me figure out why it seems like the extension is using the wrong server address? Running `p4 edit <file>` from a command window opened into the same directory **does** work, so I think my config is fine.

**Comment by stef-levesque** [comment]
You can run `Perforce: Display client/server information` from the command palette.
All other P4 commands should display in the same log window.

**Comment by tivac** [comment]
The result of running `Display client/server information` and running `p4 info` from a cmd in the same dir are identical.

This appears to be working now, not sure what changed overnight but oh well!
