### ISSUE TITLE
featurereq: Check out all modified files

### ISSUE THREAD

**Issue by Aciho** [stef-levesque/vscode-perforce#119]
Would be useful to have this as a single command, rather than having to go to each file and check it out before saving.

Alternatively, an option to auto-checkout on save would accomplish the same thing.

**Comment by stef-levesque** [comment]
There is already some settings for that:


Name | Type | Description
-- | -- | --
perforce.editOnFileSave | boolean | Automatically open a file for edit when saved
perforce.editOnFileModified | boolean | Automatically open a file for edit when Modified
perforce.addOnFileCreate | boolean | Automatically Add a file to depot when Created
perforce.deleteOnFileDelete | boolean | Automatically delete a file from depot when deleted
