### ISSUE TITLE
'p4 sync -q "null"' when used with folder vs workspace

### ISSUE THREAD

**Issue by kfsone** [stef-levesque/vscode-perforce#127]
From a fresh install:

- MacOSX VSC Version 1.21.1 (1.21.1)
- Perforce for VSC 3.1.0
- My p4 workspace maps to my ${DEV}/Projects/ folder, where the .p4config is,
- My VSC is opened to ${DEV}/Projects/Trunk/,
- ~/.p4enviro has invalid P4CLIENT and P4PORT,

   ${HOME}/.p4enviro    => P4PORT=bogus:92061 P4CLIENT=invalid
   ${HOME}/Projects
     Projects/.p4config => valid P4PORT, P4CLIENT, P4USER
     Projects/Trunk
        => files

I'm able to log in/out, but when I try to sync, output is:

p4 login -s
p4 sync -q "null"
ERROR: "null - no such file(s).\n"

After fixing the problem by copying the .p4config into the Trunk/ folder and removing the .p4enviro P4CLIENT and P4PORT fields, I was not able to recreate the problem.

**Comment by egabrum** [comment]
I have the same issue: `p4 sync -q "null"`, except that for me it does not go away . Cannot sync anything.

**Comment by stef-levesque** [comment]
@egabrum have you tried to specify your credential in you VSCode settings, as documented here? 
https://github.com/stef-levesque/vscode-perforce#activation

**Comment by egabrum** [comment]
@stef-levesque I have tried this:
```
"perforce.client": "clientName", 
"perforce.user": "userName",
"perforce.port": "serverName:1666",
"perforce.password": "myPassword",
"perforce.dir": "C:\\Users\\me\\Perforce\\clientName", //myPath
```

I can login and create changelists (not submit them because linking a job is mandatory for us and the extension does not support jobs #123 ) , but when I try to sync, it sends:
`p4.exe -c clientName sync -q "null"`
or
`p4.exe -u userName -c clientName -p serverName:1666 -P myPassword -d myPath sync -q "null"`
and I get:
`ERROR: "null - no such file(s).\r\n"`

**Comment by egabrum** [comment]
Thanks for the input @jackbrown but, no matter what I try, the "null" gets always inserted at the end of the sync command, breaking it.  
It must be the extension inserting that "null", for no good reason. This looks to me like a bug.

Am I really the only one that is having this issue????

**Comment by stef-levesque** [comment]
https://github.com/stef-levesque/vscode-perforce/blob/919095223473eb2fe24e9cf6fa5eadd8d76ee4a6/src/scm/Model.ts#L469

`config.p4Dir` do not contain the Workspace `perforce.dir` setting.

Should be replace with 

```js
const p4Dir = vscode.workspace.getConfiguration('perforce', this._workspaceUri).get('dir');
const pathToSync = p4Dir ? vscode_1.Uri.file(p4Dir + '...') : '';
Utils.runCommand(this._workspaceUri, 'sync', pathToSync, null, '').then(output => {
```

**Comment by egabrum** [comment]
I'm glad this issue is getting some love!
Looking forward to the next release. Thanks

**Comment by nonatomiclabs** [comment]
@stef-levesque Thank you for the quick answer! Do you plan to fix and release soon? I can submit a PR if you want but it's such a small fix that it's probably easier for you to do it locally?

**Comment by egabrum** [comment]
Release the fix or this cat dies ;-)

**Comment by stef-levesque** [comment]
Sry, haven't got time to GitHub lately.
I'll have a look this week.

**Comment by stef-levesque** [comment]
@egabrum @nonatomiclabs 

I've made a pre-release that include the fix. It still need some testing, but you can install it manually here:
https://github.com/stef-levesque/vscode-perforce/releases

There, you can download the `perforce-3.1.1.vsix` file and install it in VSCode with the command palette:
`Extensions: install from VSIX...`

Let me know if it solve your issue, or if it creates other problems.

**Comment by egabrum** [comment]
@stef-levesque 
I have tried the pre-release (thanks!). I don't know if this is new, but it only seems to work if I end the dir with `\\`:
`"perforce.dir": "C:\\Users\\me\\Perforce\\clientName\\",`
works
`"perforce.dir": "C:\\Users\\me\\Perforce\\clientName",`
does not work
