### ISSUE TITLE
Suggestion: Allow extension to work without opening folder

### ISSUE THREAD

**Issue by L8u8k8e8** [stef-levesque/vscode-perforce#13]
Right now you have to open a folder to allow the extension to work at all due to it's use of the per workspace configurations. It would be nice to be able to use this extension with random files that I've opened that aren't in a folder I currently have open.

Seems like you could do this in a pretty straightforward way by having a set of global settings that were able to be overridden by the local workspace settings (if set by the user for that workspace).

**Comment by cori** [comment]
+1

**Comment by jel-massih** [comment]
Opened PR for basic Add/Edit/Revert and file status when no workspace is opened.

Functions as if running p4 from the files path.

**Comment by jel-massih** [comment]
This should be fixed as of v.1.0.0
