### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by eugesd** [stef-levesque/vscode-perforce#144]
Hi, 

When I try logging in I receive this meassage:
```

p4.exe -u eugesd -c eugesd_w -p perforceserver:1666 login
ERROR: "spawn C:\\Windows\\system32\\cmd.exe ENOENT"
```

Any ideas?

Thanks,
Eugenio

**Comment by stef-levesque** [comment]
I've seen this error today with another extension, when I launched VSCode from a command prompt.

Try to re-open VSCode and log in P4 from the built-in terminal. And then re-try to log from the extension.
