### ISSUE TITLE
File(s) not opened on this client. Cannot read property 'model' of undefined

### ISSUE THREAD

**Issue by ansu0122** [stef-levesque/vscode-perforce#150]
Attempt to refresh perforce source control ends with  ERROR: "File(s) not opened on this client.\r\n". Perforce diff against the most recent revision seems to be working but 
Perforce sync - ERROR: "null - no such file(s).\r\n"
Perforce submit changelist - Cannot read property 'model' of undefined
When I edit a code I do not see that changes are being tracked in source control.
I added .p4config to root directory of the project and set the env variable. 
P4CONFIG=.p4config 
Please advise. Thanks!

**Comment by mayo** [comment]
It seems the plugin tries to sync specific files. Looking at the console when executing sync, it calls: `p4 sync -q "null"`. The p4 sync command takes an optional path, when refreshing specific files. The plugin should not provide any parameters when refreshing the whole workspace.

**Comment by mayo** [comment]
This was fixed in https://github.com/stef-levesque/vscode-perforce/releases/tag/v3.1.1-alpha (Commit 6d8dd87724075aea642d61be1a27e06c651e0d7d)
