### ISSUE TITLE
Fully busted

### ISSUE THREAD

**Issue by Ruuttu** [stef-levesque/vscode-perforce#151]
The extension seems to be broken in some fundamental way for me.

All commands say "command not found". For example when attempting to read the logs:

![vsperforce](https://user-images.githubusercontent.com/11808216/50632814-c8f86380-0f51-11e9-959b-ec67dff1227d.png)

**Comment by Ruuttu** [comment]
This is with the latest version of VS Code as of writing this.

Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

**Comment by jel-massih** [comment]
Please follow the instructions in https://github.com/stef-levesque/vscode-perforce#activation

Reopen this issue if this doesn't fix your issue.
