### ISSUE TITLE
Settings are present and set up, but nothing shows in "Source Control" and all command palette options say "not found"

### ISSUE THREAD

**Issue by Deco** [stef-levesque/vscode-perforce#152]
For example, "Perforce: Show Output" produces this error:

`
command 'perforce.showOutput' not found
`

I can't see any evidence of the extension working, except for the settings section and the entries in the command palette. Either something is wrong, or this extension is really confusing to set up.

VS code info:
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

No other extensions installed.

Please help :)

**Comment by VinayGupta23** [comment]
@stef-levesque: Please help! I am facing the exact same issue, it's like not having the plug-in at all :(

**Comment by NSExceptional** [comment]
Also having this issue. Did a VS Code update break it maybe?

**Comment by stef-levesque** [comment]
Are you sure you have a folder opened in VSCode when trying to execute the extension ?

Can you try to change the activation mode to Always in your settings?

**Comment by NSExceptional** [comment]
Yes.

Setting to "always" fixed it. Not sure what happened…

**Comment by cyliang** [comment]
I also have this issue. Setting the activation mode to "Always" does not work.

**Comment by NSExceptional** [comment]
Not sure why @stef-levesque closed the issue, it's clearly not resolved…
