### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vptrbv** [stef-levesque/vscode-perforce#158]
- Issue Type: `Performance`
- Extension Name: `perforce`
- Extension Version: `3.1.0`
- OS Version: `Linux x64 4.18.0-17-generic`
- VSCode version: `1.33.0`

slevesque.perforce-unresponsive.cpuprofile.txt here:
https://gist.github.com/vptrbv/5c81537c43220206b472e226afaddffd

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by poterba** [comment]
It seems I've accidentally deleted those gists, so issue became irrelevant.
