### ISSUE TITLE
Perforce.editOnFileSave workspace setting not working as expected.

### ISSUE THREAD

**Issue by globalroo** [stef-levesque/vscode-perforce#16]
- VSCode Version: 1.1.0
- OS Version: Windows 7

Steps to Reproduce:
1. Open User settings, set "_**perforce.editOnFileSave**_": true,
2. Restart VS Code
3. Edit file in workspace
4. Save
5. File is write protect, VS Code asks if you want to overwrite, save or discard.

Additional information: 
The file mentioned above can be checked out using the plugin menu, manually.
**_editOnFileModified _** is working as expected.

Thanks for the plugin, it's been really helpful.

Andy.

**Comment by stef-levesque** [comment]
Works as designed.

The issue have been discussed in #4 

> VSCode doesnt have a presave hook so you have to choose "overwrite" when saving an existing file the first time if write protected.

Until Microsoft/vscode#239 is resolved, we don't have way to do that in an extension

**Comment by coli** [comment]
@stef-levesque #239 is resolved!

**Comment by stef-levesque** [comment]
You can expect a vscode-perforce update very soon ;)

**Comment by globalroo** [comment]
Sorry for the late reply :) thanks!

**Comment by jel-massih** [comment]
Opened PR #25  for this.

**Comment by jel-massih** [comment]
This should be fixed now. Please install latest version vscode-perforce@1.0.0
