### ISSUE TITLE
Remote development seem not working

### ISSUE THREAD

**Issue by omeijer** [stef-levesque/vscode-perforce#164]
The new Remote Development option is not yet fully working with Perforce.
It does seem to make a connection to the perforce server. 
I also see all available changelists, and are able to open a file via a changelist.

However the diff view seems to be stuck forever when activated.
Also the p4 command menu in the bottom bar seems to be non functional.
It give a client error, looks like it is using a default client and port number
instead of the one from the remote directory.

**Comment by slopez-lab** [comment]
$ autoninja -C out/Default cast_shell_apk

**Comment by slopez-lab** [comment]
third_party/android_sdk/public/platform-tools/adb devices

**Comment by slopez-lab** [comment]
autoninja -C out/Release cast_shell_apk

**Comment by omeijer** [comment]
I'm not sure what I can do with the latest replies.
They seem to be related to Android and i'm working on Linux. 
Even worse we have large clusters and as programers we are not able to install whatever we like
on those systems. Just getting VSCode installed is already a lot of hassle to us.

**Comment by omeijer** [comment]
It seems that the latest version solved all my issues.
Thanks

**Comment by davidritter** [comment]
It was working for me and the latest update seems to have broken the plugin entirely.
