### ISSUE TITLE
Enhancement: "p4 edit" on Save

### ISSUE THREAD

**Issue by hoovercj** [stef-levesque/vscode-perforce#17]
It would be nice to be able to automatically "p4 edit" a file on saving rather than manually running the command.

Should be very easy when a presave event gets added to the api. I'd be happy to add it.

https://github.com/Microsoft/vscode/issues/239

**Comment by stef-levesque** [comment]
That's exactly what we were discussing in #4 :)
Hopefully the insider build should provide it this month

**Comment by hoovercj** [comment]
Oh great, awesome.

**Comment by mightycoco** [comment]
The p4 plugin in eclipse checks out the file in question as soon as you start typing (the files are read-only on disk before being checked out)

Maybe one could achieve the same using the workspace.onDidChangeTextDocument event? I'm not sure, when this get's fired, though...

**Comment by stef-levesque** [comment]
@mightycoco can you try to add `"perforce.editOnFileModified": true` in your settings and restart your editor ? This works fine for me.

**Comment by stef-levesque** [comment]
Closing for now, as @jel-massih contribution allows to `editOnFileSave` and `editOnFileModified`
