### ISSUE TITLE
Is there any step by step way to get this working.

### ISSUE THREAD

**Issue by mrgurdeep** [stef-levesque/vscode-perforce#170]
I have installed the plugin. Restarted vs code still getting message No source control providers registered.

**Comment by mmakrzem** [comment]
After updating to the latest version of Visual Studio Code - Insiders Edition, this plugin has stopped working!

**Comment by nigelorr** [comment]
I had the same problem as @mrgurdeep , installed, set activation mode to always, added in server, user, password, client details, but nothing appeared in source control settings even after restarts of VS Code and reboots of machine.
I uninstalled and reinstalled the extension, and after a delay of a minute or so the perforce provider appeared.
However, it doesn't seem to have connected properly. If I select 'Display client/server information', it shows two commands like below but no resulting output

```
p4.exe -u MyUserName -c MyWorkspace -p ssl:MyServer:1666 -P MyTopSecretPassword info
p4.exe -u MyUserName -c MyWorkspace -p ssl:MyServer:1666 -P MyTopSecretPassword set -q
```
If I copy either of the above lines to a command prompt, I get the expected client/server information. Installation details below:

```
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134
```

**Comment by mrgurdeep** [comment]
Thanks @nigelorr Uninstalling and Reinstalling worked for me and now working fine for me.

Prerequisite is to have command line client installed.

1. Install extension 
Perforce for VS Code by slevesque (slevesque.perforce)

2. Changes to settings.json 
```
"perforce.client": "your_client",
"perforce.user": "user",
"perforce.port": "path_of_perforce_server", // something:1666
"perforce.path": "C:\\Program Files\\Perforce\\p4", // make sure you have p4 command line client installed
"perforce.editOnFileModified": true,
"perforce.editOnFileSave": true,
"perforce.addOnFileCreate": true
```

3. Check if you see in source control tab
 
4. If not uninstall. Close VS code and reinstall. You will see it this time.
