### ISSUE TITLE
Login/connect to a Perforce server using username/password

### ISSUE THREAD

**Issue by tohidazizi** [stef-levesque/vscode-perforce#18]
The extension keeps denying any request with this error message:

> Perforce Log Output
> p4.exe info
> ERROR:
> Error: Command failed: p4.exe print -q -o "_C:\Users...\AppData\Local\Temp\tmp-....._" "_c:\p4......_"
> _c:\p4......_ - must create client '_my-computer-name_' to access local files.

**Comment by stef-levesque** [comment]
Can you confirm you have a `.p4settings` file and you are logged in ?

**Comment by stef-levesque** [comment]
Please update to version 1.1.0 and try the `login` command.
