### ISSUE TITLE
ERROR: "Usage: annotate [ -aciIqt -d<flags> ] files...\r\nInvalid option: -u.\r\n"

### ISSUE THREAD

**Issue by rghan0001** [stef-levesque/vscode-perforce#194]
p4  annotate -qu filepath
There was an error when using the above command:
ERROR: "Usage: annotate [ -aciIqt -d<flags> ] files...\r\nInvalid option: -u.\r\n"

my p4 version: 2013.2

https://www.perforce.com/manuals/v15.1/cmdref/p4_opened.html#p4_opened.examples
I not found "-u" parameters in the link above

help !

**Comment by maciejmatczak** [comment]
That one is quite old.. Newer Perforce versions should have it: https://www.perforce.com/manuals/cmdref/Content/CmdRef/p4_annotate.html?Highlight=-u#Options_..918

Generally, first try https://github.com/mjcrouch/vscode-perforce and recreate issue there if problem still persists.

**Comment by stef-levesque** [comment]
Please use the [2020 fork by mjcrouch](/mjcrouch/vscode-perforce)
My extension is deprecated.
