### ISSUE TITLE
File is not under client's root

### ISSUE THREAD

**Issue by SnareHanger** [stef-levesque/vscode-perforce#2]
Possibly a conflict with the sublime perforce plugin, but I can seem to get the edit command to work.

I get the following:
```
p4.exe edit "c:\Users\snarehanger\Documents\Development\project\proj\js\v2\components\elements\MultiFileUploader.jsx"
    
ERROR:
Path 'c:\Users\snarehanger\Documents\Development\project\proj\js\v2\components\elements\MultiFileUploader.jsx' is not under client's root 'c:\Users\snarehanger\AppData\Roaming\Sublime Text 3\Packages\User'.
```

Possibly a p4 configuration issue, but any ideas on this?

**Comment by stef-levesque** [comment]
Hm, maybe look at your P4 Environment Settings, see if you have the right P4CLIENT setup.
Otherwise, you can add a .p4config file at the root of your project to change your settings.

**Comment by SnareHanger** [comment]
```
p4 set
``` 
shows that P4CLIENT is set as the workspace name, P4EDITOR is set as C:\Program Files (x86)\Microsoft VS Code\code.exe.  

Why would the sublime path be brought into this?

**Comment by stef-levesque** [comment]
Having the correct cwd might help. Try updating to vscode-perforce@0.1.2

**Comment by SnareHanger** [comment]
Perfect!  Thanks!
