### ISSUE TITLE
Show warning when checking out outdated file

### ISSUE THREAD

**Issue by Franziskus1988** [stef-levesque/vscode-perforce#24]
Currently you don't get any warning when you edit an outdated file. This is sometimes annoying, because one has to merge after editing the file. When getting a warning with a "get latest revision" button one could avoid this. 

As solution one could diff current revision against revision on head  with `p4 fstat -T "headRev" %file` and `p4 fstat -T "haveRev" %file`.

**Comment by Franziskus1988** [comment]
@stef-levesque Do you plan to tackle this, or should I fork, do it on my own and request a pull?

**Comment by stef-levesque** [comment]
I'll be busy with other things, so feel free to take this and make an PR :)
