### ISSUE TITLE
Honor .p4ignore for delete

### ISSUE THREAD

**Issue by unional** [stef-levesque/vscode-perforce#27]
I have `node_modules` ignored (of course), but when I update a package, it tries to run `p4.exe delete <file in node_modules>`.

With `perforce.deleteOnFileDelete` turned on.

**Comment by jel-massih** [comment]
I believe this will also be an issue with Add/Edit. 

Do you have any files within an ignored folder in your depot?
p4 delete on a file not on the client should effectively be a no-op

**Comment by unional** [comment]
I think add/edit is working fine. I don't see the extra output in the log.

Yes it's no-op, but the output is...

![image](https://cloud.githubusercontent.com/assets/3254987/21281980/aae0dfd4-c3a5-11e6-9cc6-e6210c9f60fd.png)
