### ISSUE TITLE
Do not execute if cwd is not under p4

### ISSUE THREAD

**Issue by unional** [stef-levesque/vscode-perforce#33]
vscode-perforce: 1.0.0

```sh
p4 info

Client root: e:\hwong\p4\
Current directory e:\hwong\somewhere-else\
```

p4 should not be invoked.

**Comment by maxnoel** [comment]
Update 2.0.0 (with VS Code 1.11.1) causes the error window to pop up every time a file or folder is opened that's not managed by Perforce:

Error: Command failed: p4.exe print -q [filename]
Path [filename] is not under client's root [p4 client root folder]

**Comment by jel-massih** [comment]
Yeah, getting a fair number of complaints about that. Looking into a few options to resolve/alleviate this issue.

**Comment by maxnoel** [comment]
Note: disabling the editOnFileSave/addOnFileCreate/deleteOnFileDelete options alleviates the issue a little bit (you no longer get errors every time you save a file).

**Comment by stef-levesque** [comment]
This come from the editor, calling QuickDiffProvider.provideOriginalResource(...) on any open text document

**Comment by stef-levesque** [comment]
@jel-massih please review 0b7dbf7 and let me know if it's a viable solution

**Comment by stef-levesque** [comment]
@maxnoel @jel-massih please update to version 2.0.1

**Comment by jel-massih** [comment]
@stef-levesque Sweet, digging the removal of Channel.Show()

**Comment by maxnoel** [comment]
@stef-levesque 2.0.1 appears to fix my issue. Thank you!

**Comment by stef-levesque** [comment]
:+1:
