### ISSUE TITLE
Can no longer use edit command since 1.0

### ISSUE THREAD

**Issue by kLy** [stef-levesque/vscode-perforce#34]
Since the 1.0 update the edit command no longer works. The icon also doesn't correctly reflect the file's status any more.

Using p4 edit from the command line still works the same.

This was not an issue in the previous version.

**Comment by jel-massih** [comment]
Hey,

Having Trouble Reproducing this.

Do you have a folder opened?

If you run the Perforce: Show Output Command and then run edit, what is the output?

**Comment by jel-massih** [comment]
Closing this as can not replicate. If it is still an issue, feel free to open a new issue.
