### ISSUE TITLE
What is the reason to do `export namespace XYZ`?

### ISSUE THREAD

**Issue by unional** [stef-levesque/vscode-perforce#35]
I'm considering to contribute to the code so I want to understand the code first.

Is there a reason for that?

It seems like it is extra to me because at consumption you do
```ts
import {PerforceCommands} from './PerforceCommands'
```
It is the same if you remove the namespace and import as:
```ts
import * as PerforceCommands from './PerforceCommands'

// or better
import { registerCommands } from './PerforceCommands'

export function activate(...) {
  registerCommands()
}
```

**Comment by jel-massih** [comment]
The decision to use namespace was made because
1. Want to expose many functions without having too manually specify each function.
2. Do not want to use * because it feels wrong.
3. Do not want to use a Class because it feels wrong.

2 and 3 were just personal preferences and are more or less arbitrary.

May I ask what is the problem with this implementation is? The alternatives you mentioned seem equavalent.

**Comment by unional** [comment]
It's just more align with how ES6 is written and used.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

TypeScript is JavaScript so I typically see and encourage to write TypeScript just like JavaScript.

With the advance of module, there is less of a need to use namespace.
Of course, there are still cases where namespace is useful. Most noticeably:

```ts
export function foo(options: foo.Options) { ... }
export namespace foo {
  export function boo() { ... }
  export interface Options {
    ....
  }
}
```

**Comment by unional** [comment]
Another reason that exporting the function directly is better than namespace is because of tree-shaking.
It doesn't apply here because these are all internal, but when exporting externally, if the consumer only use part of your library and import them as:

```ts
import { func1, func2 } from 'your-library'
```

Then during bundling tree shaking can take place to bundle only the part that is relevant thus reducing the size of the bundle.

**Comment by Franziskus1988** [comment]
Maybe you should read the modules chapter in the typescript handbook. Especially the "Do not use namespaces in modules" section. 😀

**Comment by unional** [comment]
@Franziskus1988 that is no such section as of now. 😛  or at least I can't find it.

> Do not use namespaces in modules

As a general direction it is true thou. 👍

**Comment by Franziskus1988** [comment]
Here at the bottom: https://www.typescriptlang.org/docs/handbook/modules.html

Or read:
https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html

**Comment by stef-levesque** [comment]
Closing for now, please reopen if anyone want to look at it.
