### ISSUE TITLE
Add keyboard shortcuts to p4 diff

### ISSUE THREAD

**Issue by DusanNikolov** [stef-levesque/vscode-perforce#38]
::RFE::
There is no option of setting keyboard shortcuts for going back and forth when using perforce diff in visual studio code.
This enhancement would be very useful, since using mouse to click on top right corner arrows is not practical at all, and all diff tools have this one implemented either via Fx keys or Ctrl+1/2 combo.

**Comment by stef-levesque** [comment]
you can use the official VSCode commands, which are:
* `workbench.action.compareEditor.nextChange`
* `workbench.action.compareEditor.previousChange`

Here is how I setup my `keybindings.json`:
```json
[
{ "key": "ctrl+n",          "command": "workbench.action.compareEditor.nextChange",
                               "when": "textCompareEditorVisible"},

{ "key": "ctrl+p",          "command": "workbench.action.compareEditor.previousChange",
                               "when": "textCompareEditorVisible"}
]
```

Hope it helps!

**Comment by DusanNikolov** [comment]
Thanks a bunch! Works great.

**Comment by DusanNikolov** [comment]
Hey, I have another issue popping up right now.

Before, when I tried to execute: "diff" in vs code, it was opening p4 diff
of my modified file with the latest revision of depot file.
Now that doesn't seem to work and I have to use the other command: p4 diff
revision <rev_number>...

The output that I get from running p4 diff is:
Invalid revision number 'null'.
p4.exe info
p4.exe edit extension-output-#1
ERROR:
A revision specification (# or @) cannot be used here.

**Comment by stef-levesque** [comment]
there must be something wrong with the file path. Do you have any special character in the files causing problems ?

**Comment by DusanNikolov** [comment]
No, not really. Not even spaces. This is the path (I just replaced some
words with username and example).
p4.exe opened c:\p4\sw\example\JsonUtils.cpp
p4.exe print -q -o
"C:\Users\username\AppData\Local\Temp\tmp-14724ci9tKDoA150x.cpp"
"c:\p4\sw\example\JsonUtils.cpp#null"
ERROR:
Error: Command failed: p4.exe print -q -o
"C:\Users\username\AppData\Local\Temp\tmp-14724ci9tKDoA150x.cpp"
"c:\p4\sw\example\JsonUtils.cpp#null"
Invalid revision number 'null'.
p4.exe info
p4.exe edit extension-output-#1
ERROR:
A revision specification (# or @) cannot be used here.

**Comment by DusanNikolov** [comment]
Hey is there something else that I can try, regular diff is still not working for me. Tried to reinstall the extension, but didn't help. It's still displaying the same error message in the output...

Are there some logs that I can look at apart from the output to see what is wrong?

**Comment by DusanNikolov** [comment]
Nevermind, found that using the other command with not specifying revision number gives me diff with latest revision in the depot. So a workaround.

**Comment by stef-levesque** [comment]
Glad you found a workaround! I'm working on a more robust way to handle file path, coming up in the next release.

**Comment by DusanNikolov** [comment]
Thanks for the update!
