### ISSUE TITLE
SCM providers for vscode is now available

### ISSUE THREAD

**Issue by unional** [stef-levesque/vscode-perforce#39]
http://code.visualstudio.com/updates/v1_10#_contributable-scm-providers

**Comment by stef-levesque** [comment]
Yes, this is part of the plan! :)

**Comment by hoovercj** [comment]
Let me know if you want help with this feature, I'm very interested in seeing if we can use this as well. You might have heard that parts of Microsoft use Source Depot which is a fork of Perforce (which is why I submitted a PR to allow configuring the executable for this extension)

Depending on how you implement the SCM provider, it might continue to work with Source Depot which would be fantastic :-)

**Comment by stef-levesque** [comment]
That's a good thing to know!

Source Depot seems to be proprietary to Microsoft, I couldn't find much info on the differences with 'vanilla' Perforce. 

Please let me know if there is anything I can do to make it customizable enable to support it.

**Comment by hoovercj** [comment]
So far the "add" and "edit" and "diff" commands are working and that's about the most I've needed it for.

But now that there is a possibility for slightly deeper integration, I'm interested in seeing how it can work. If I'm not mistaken, there isn't an official API out, right? The vscode team is just moving the git support out into an extension and building the API that way with hopes that in April or May there will be something more concrete?

At that point I'd be happy to look at it and look at what you have and see if I think there will be problems. I don't expect 100% support, of course, only to avoid unnecessary feature gaps.

**Comment by stef-levesque** [comment]
Work in Progress
![screen shot 2017-03-26 at 4 07 54 pm](https://cloud.githubusercontent.com/assets/7251102/24334790/cfd7c996-123e-11e7-943f-25d428f89965.png)

**Comment by stef-levesque** [comment]
Now supported in version 2.0.0.

Please let me know if there is any compatibility issue with Source Depot
