### ISSUE TITLE
p4 sync

### ISSUE THREAD

**Issue by cyenko** [stef-levesque/vscode-perforce#40]
Morning! Really enjoy using this at the workplace, so thanks for this.

Is there a reason why the p4 sync command hasn't been included? If no reason, happy to dev and pull it in.

Thanks,
Christian

**Comment by stef-levesque** [comment]
No particular reason, really :)

I usually use outside tools to sync and merge, so I didn't think of including it in the editor.

I would guess duplicating the behaviour of `info`, and simply displaying the output in the `Perforce Log` should suffise for now.

I'm currently busy with #39 , so I might not look at it right away. Feel free to PR if you want to 👍
