### ISSUE TITLE
Resolve real path

### ISSUE THREAD

**Issue by silenaker** [stef-levesque/vscode-perforce#42]
I have linked files in my project folder whose paths are not in perforce depot, so p4 edit command is not effect, please resolve the symlink path to real path by executing commands

**Comment by stef-levesque** [comment]
Please update to version 2.0.1, and try to set `perforce.realpath: true` in your settings.
Let me know if it fixes your problem.

**Comment by silenaker** [comment]
Thanks for your great job! All commands work fine for me.
