### ISSUE TITLE
Add quotes around file paths passed to commands

### ISSUE THREAD

**Issue by eeroh** [stef-levesque/vscode-perforce#43]
Currently the commands do not work properly if there are spaces in the file paths. Please add quotes around the paths that are passed to executed perforce commands.

This has worked in earlier versions, at least in 0.1.8 where the quotes were added to all paths, but the functionality has apparently broken in the refactoring done for the latest 1.0.0 version.

**Comment by stef-levesque** [comment]
Hi @eeroh ,

Quotes are still used for most file path, afaik. 
Could you be more specific about which command failed, and what is the file path used ? This may actually be caused by special character, like in issue #38, which commit 0efcd4a should fix.

**Comment by eeroh** [comment]
Hi @stef-levesque, sure, here's an example:

When trying to check out a file for edit in VS Code, the operation prints to the Perforce log rows like
```
p4 edit /Users/eero/Perforce/eero.ws/Project/Assets/Lib/Scripts/Editor/Object Extensions for Editor/ObjectExtensions.cs
```
and spaces seem to cause the operation to fail, because for any file in other folders without spaces checking out for edit works.

In this case I'm operating on OS X, and the corresponding command in terminal fails due to not having quotes around the full path, but the same should apply on any operating system.

What's more, by editing /Users/eero/.vscode/extensions/slevesque.perforce-1.0.0/out/src/PerforceCommands.js, it's easy to check that by adding quotes the issue gets fixed.
For example by making a quick hack to function editOpenFile() in the form of
```
    function editOpenFile() {
        var editor = vscode_1.window.activeTextEditor;
        if (!checkFileSelected()) {
            return false;
        }
        var filePath = editor.document.uri.fsPath;
        //If folder not opened, run p4 in files folder.
        if (checkFolderOpened()) {
            edit(addQuotes(filePath));
        }
        else {
            edit(addQuotes(filePath), addQuotes(Path.dirname(filePath)));
        }
    }
    // HACK: temp utility function
    function addQuotes(str) {
        return (str) ? ('"' + str + '"') : str;
    }
```
the functionality starts working, and the command in the Perforce log of vs code shows up as
```
p4 edit "/Users/eero/Perforce/eero.ws/Project/Assets/Lib/Scripts/Editor/Object Extensions for Editor/ObjectExtensions.cs"
//depot/Project/Assets/Lib/Scripts/Editor/Object Extensions for Editor/ObjectExtensions.cs#3 - opened for edit
```
Now, since it's best to make a neat implementation, I'd really appreciate if you took a look at this to replace my hacks made in a language I hardly use.


Comparing to earlier versions (0.1.8 or 0.1.9), there the code actually did explicitly add the quotes like 
```
function p_editUri(uri) {
	var cmdline = buildCmdline("edit", '"' + uri.fsPath + '"');
...
```
and so on, but in 1.0.0, following any similar uri.fsPath parameters in PerforceCommands.js shows that the quotes do not get similarly added (not on PerforceService.js side either), so that might have just dropped off in some point.

Anyways, thanks for the quick response, and I hope this clarified the issue.
-Eero

**Comment by stef-levesque** [comment]
Thanks for the detailed explanation, much appreciated :+1: 

Yes, I see the problem now... All file paths used in P4 command should be surrounded by quote, and ASCII expanded to avoid special character. We already do that in [Utils.ts](/stef-levesque/vscode-perforce/blob/scm/src/Utils.ts) on the `scm` branch.

Unfortunately, this fix will only be compatible with VSCode March release (v 1.11). See Microsoft/vscode#23276 for ETA.

I hope to push a new release over the week-end. In the meanwhile, your local fix seems like a decent workaround for the `edit` command. Although, `addQuotes(...)` should be used everywhere we use fsPath. I will try to push an emergency release your fix in.

Thanks again for your help!

**Comment by stef-levesque** [comment]
Fixed. Please update to version 1.1.0

**Comment by eeroh** [comment]
Oh wow, that was fast. Updated and it works :+1: Thanks for fixing this!
