### ISSUE TITLE
VSCode Engine 1.11.1 causes npm install error

### ISSUE THREAD

**Issue by hoovercj** [stef-levesque/vscode-perforce#46]
I updated to the v1.11.1 and ran npm install and got this:

```
node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.11.1
Found minimal version that qualifies engine range: 1.11.1
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/1.11.1/src/vs/vscode.d.ts
Error installing vscode.d.ts: Error: Request returned status code: 404
Details: 404: Not Found
```

**Comment by stef-levesque** [comment]
https://raw.githubusercontent.com/Microsoft/vscode/1.11.1/src/vs/vscode.d.ts works fine. Maybe a fluke from Github ?

**Comment by hoovercj** [comment]
Yeah, it 404d me in my browser earlier but seems ok now. I'll change it back later and check.

**Comment by stef-levesque** [comment]
I also got a few hiccup with GitHub today, but all seems fine now. Closing it.
