### ISSUE TITLE
Performance Concerns

### ISSUE THREAD

**Issue by hoovercj** [stef-levesque/vscode-perforce#51]
Almost every action clears the resource list and does a complete refresh.

Some changes such as moving a file to a new changelist, marking a file for "edit", etc. could be handled by updating the resources data structure without a refresh.

Also, the overall performance seems very slow. A refresh on my machine takes ~20 seconds whereas using refresh in a standalone tool we have takes less than 10.

**Comment by stef-levesque** [comment]
I would be curious to see the Perforce Output of that refresh (i.e. how much files, changelists are involved)

It could be a good idea to add timestamp on the output too.

**Comment by hoovercj** [comment]
I think it has to do with fstat. I think fstat takes about 1 second-ish per file as seen here with a small powershell script.

``` 
C:\path> $StopWatch = New-Object -TypeName System.Diagnostics.Stopwatch; $StopWatch.Start(); for ($i=1; $i -le 20; $i++) { sd fstat //depot/path/to/file > $null } $StopWatch.Stop() ; $StopWatch.Elapsed ; $StopWatch.Reset() ;

TotalSeconds      : 20.11306
```

**Comment by hoovercj** [comment]
It would be lame if the slowdown is caused by not being able to use the ztag flag for sd, but that's something you could compare with perforce. The time to execute fstat with and without `ztag -T clientFile`

**Comment by hoovercj** [comment]
`sd where` seems to be about 40% faster. Running 20 times on the same file took only 13 seconds instead of 20.

**Comment by hoovercj** [comment]
Ah ok, I actually have a solution. They just need batched as one command, then it will only take one second. I'll go ahead and submit a PR shortly

**Comment by stef-levesque** [comment]
Seems like a proper solution !

**Comment by stef-levesque** [comment]
Just pushed version 2.0.1.
