### ISSUE TITLE
P4 commands in output even when git selected as SCM provider.

### ISSUE THREAD

**Issue by jaredwy** [stef-levesque/vscode-perforce#54]
Since the last version even when I have git selected as my SCM provider I am getting p4 output in my console.

It is pretty noisy. See the attached screenshot. I have had to disable the p4 plugin in the workspaces that use git.

<img width="1901" alt="settings_json_-_llvm-opt-view" src="https://cloud.githubusercontent.com/assets/297079/24841297/cf5ada3a-1dc4-11e7-8d0f-abe08a23f972.png">

**Comment by stef-levesque** [comment]
We are aware of the issue. A fix is already in. A new version of the extension should be publish soon.

**Comment by jaredwy** [comment]
Great thanks!

**Comment by stef-levesque** [comment]
Less intrusive errors in version 2.0.1, please update.

**Comment by jaredwy** [comment]
@stef-levesque unfortunatly this doesn't seem fixed. 

Just updated, reset vscode and upon opening.

```
p4 print -q "/Users/wyles/src/llvm-opt-view/src/OptStreamTransformer.js"
p4 login -s
ERROR:
Error: Command failed: p4 print -q "/Users/wyles/src/llvm-opt-view/src/OptStreamTransformer.js"
Path '/Users/wyles/src/llvm-opt-view/src/OptStreamTransformer.js' is not under client's root '/Users/wyles/perforce'.
```
