### ISSUE TITLE
Information Message

### ISSUE THREAD

**Issue by Franziskus1988** [stef-levesque/vscode-perforce#7]
I think it would be a good idea to replace the information message with a statusbar message, because it's annoying to always click the appearing message box. 
So instead of: 
showInformationMessage("blabla") 
you could use:
setStatusBarMessage("blabla", 3000) //Statusbar message that disappears after 3 seconds.

**Comment by stef-levesque** [comment]
You're right. Ideally, a status bar icon or a decorations to the explorer would be even less intrusive.

**Comment by stef-levesque** [comment]
I change some of the messages for StatusBar instead, try updating to vscode-perforce@0.1.3
