### ISSUE TITLE
Option to open file editor from Source Control sidebar.

### ISSUE THREAD

**Issue by NeroProtagonist** [stef-levesque/vscode-perforce#70]
I would like to easily open a file listed in the source control sidebar in a default editing window rather than a diff view.

Could you please add a config option to make this the default behaviour or alternatively open the editor with a modifier key + left click or middle click or something.

Thanks

**Comment by stef-levesque** [comment]
Fixed in version 2.2.0.
Please update and try the new setting `perforce.scmFileChanges`
