### ISSUE TITLE
Project based settings

### ISSUE THREAD

**Issue by omeijer** [stef-levesque/vscode-perforce#71]
Hi
i'm using your tool everyday but there is this little thing that I either don't understand or not available.
We typically use new clients and port settings for every project,
So we have files called .p4config that contains:
P4PORT=<server>:<port>
P4CLIENT=<clientname>

could you tool detect these files and use these settings so when we jump from one project to another 
we do not need to start VSCode with new settings?

Otto

**Comment by stef-levesque** [comment]
Hey Otto,

By default, the extension will let P4 decide what are the client and port settings. From my understanding, P4 will go up in the folder hierarchy until it find a specific filename, specified from the environment variables (usually `.p4config`). 

If you already have such a file, it should already be working. I would suggest you try to run `perforce.info - Display client/server information` to get more info on what's happening.

Now, you can manually set `perforce.client` in your vscode user or workspace settings, but unfortunately the `port` is not exposed yet.

**Comment by omeijer** [comment]
You are right, I accidentally removed my P4CONFIG variable so it no longer detects the .p4config files.
With that variable set everything works like a charm, thanks for the info and quick response.
