### ISSUE TITLE
Submit Default Changelist

### ISSUE THREAD

**Issue by dolphy01** [stef-levesque/vscode-perforce#72]
This is a feature request to be able to directly submit the default changelist.

Checked out items are currently added to the default changelist, but there is no immediate way to submit those changes. The workflow required is to:
* create a new "named" changelist
* move checked out items of interest to the "named" changelist
* submit the "named" changelist

This feature should allow:
* "one click submit" of the default changelist...this is add the little check-marky submit button which will immediately submit the default changelist
* adding a description to the default changelist before submission should be *optional*, it defeats the "one click submit" nature to require an added description...perhaps this can be options driven
* a keyboard shortcut for "submit default changelist" would be desirable

The combination of these three behaviors would allow for very fast iterative development in appropriately equipped environments.

**Comment by vrachels** [comment]
see https://github.com/stef-levesque/vscode-perforce/pull/87

**Comment by stef-levesque** [comment]
Now part of version 2.2.0!
