### ISSUE TITLE
Do not enable extension when root is not under p4 workspace

### ISSUE THREAD

**Issue by unional** [stef-levesque/vscode-perforce#74]
```sh
- p4-workspace-root
- git-projects
  - git-project1
```

When opening the `git-projects/git-project1` folder, the P4 extension is still enabled.
User has to switch SCM manually everytime when the folder is opened:
![image](https://cloud.githubusercontent.com/assets/3254987/26261669/f9ee99ae-3c86-11e7-8a86-276dda19b482.png)

**Comment by stef-levesque** [comment]
It is VSCode responsibility to remember the user's choice. If this is not working, an issue should be logged on their side.

**Comment by unional** [comment]
I see. Didn't notice Git is available in non-git folder.
I notice SCM git is not available when a new vscode is opened (empty, without folder)

**Comment by stef-levesque** [comment]
I could probably solve that last part (no Perforce SCM on empty folder)

**Comment by stef-levesque** [comment]
Should be fixed in version 2.2.0, please update.
