### ISSUE TITLE
Add ability to select perforce client in settings

### ISSUE THREAD

**Issue by Tazeela** [stef-levesque/vscode-perforce#76]
I have multiple perforce clients and would like to be able to select which perforce client a project uses, rather then create a new client. It would be great to have a setting for this, E.G. "perforce.clientName" which I could use to override the clientname. 

I tried changing "perforce.command" to "p4.exe -c <clientName>" but it gives an error because the value of command gets wrapped with double quotes.

To select a client you would pass -c <clientName> as an argument to p4.exe.

**Comment by Tazeela** [comment]
Looking at the code this actually is supported its just not documented. The setting is perforce.client

**Comment by stef-levesque** [comment]
This feature came from a PR (#19, thanks @ralberts) but you're right, it is not documented.
My bad, I'll update the `README.md` file, and `package.json` so it can be suggested when editing VSCode settings.

Also, you can create a `.p4config` files at the root of your workspace to let P4 knows what should be the default values for P4CLIENT, P4USER and P4PORT.

**Comment by ralberts** [comment]
Sorry all!  Thanks @stef-levesque !!

**Comment by stef-levesque** [comment]
Now part of version 2.2.0, please update.
