### ISSUE TITLE
Automatically uncheck file after undoing latest changes

### ISSUE THREAD

**Issue by TheHolyWaffle** [stef-levesque/vscode-perforce#77]
This ia suggestion for when perforce.editOnFileModified is true.

Imagine opening a file that is not yet checked out in a changelist and you start modifying it and afterwards save the changes. The file is now automatically checked out and put in the default changelist.

Now keep doing CTRL+Z in VSCcode until all changes are undone and the document is exactly the same as it was before. The perforce plugin should automatically detect this and also revert/uncheck the file out of the changelist.

**Comment by stef-levesque** [comment]
I usually use `Revert Unchanged Files` on a changelist, whenever I suspect it is the case.
But I agree an automatic check on saved files would make sense.

**Comment by hsnmck** [comment]
How do you Revert Unchanged Files on a changelist in vscode?
