### ISSUE TITLE
Unable to login to perforce

### ISSUE THREAD

**Issue by Mashewnutz** [stef-levesque/vscode-perforce#78]
Hey,

I am trying to use this integration for perforce which seems very handy!

Unfortunately I can't get it working. At all. 

When I try to login to perforce via vscode I get this error message:
Perforce: Command failed: p4 login

However, from the same folder if I open a terminal and type 'p4 login', then enter the same password it succeeds.

Any ideas what is going on here?

**Comment by stef-levesque** [comment]
Do you get a prompt to enter your password? Any output at all in `Perforce Log` ?

**Comment by stef-levesque** [comment]
Please update to version 2.1.1 and see if you get more detailed errors in `Perforce Logs`

**Comment by Mashewnutz** [comment]
How should I even view the perforce logs?

**Comment by stef-levesque** [comment]
![screenshot_2017-06-28 12 24 10_5gymgp](https://user-images.githubusercontent.com/7251102/27648505-c8663d70-5bfc-11e7-9e6e-a0f4322d1165.png)

**Comment by Mashewnutz** [comment]
This is the output I get:
p4 login -s
ERROR:
Error: Command failed: p4 login -s
/bin/sh: p4: command not found
ERROR:
/bin/sh: p4: command not found
p4 login -s
ERROR:
Error: Command failed: p4 login -s
/bin/sh: p4: command not found
ERROR:
/bin/sh: p4: command not found
ERROR:
Error: Command failed: p4 login -s
/bin/sh: p4: command not found
p4 login -s
p4 login
ERROR:
Command failed: p4 login
/bin/sh: p4: command not found

**Comment by Mashewnutz** [comment]
I have p4 located at /usr/local/bin/p4

**Comment by stef-levesque** [comment]
Can you try to add the following in your vscode `User Settings` and reload ?
```javascript
"perforce.command": "/usr/local/bin/p4"
```

**Comment by Mashewnutz** [comment]
OK this is the output I get now:
"/usr/local/bin/p4" opened "/Users/mattcas/Library/Application Support/Code/User/settings.json"
"/usr/local/bin/p4" login -s
ERROR:
Error: Command failed: "/usr/local/bin/p4" login -s
Perforce client error:
	Connect to server failed; check $P4PORT.
	TCP connect to perforce:1666 failed.
	nodename nor servname provided, or not known

I have a .p4config file located at the root of my folder opened from vscode

**Comment by stef-levesque** [comment]
Shouldn't it be `.p4settings` ?

Type this in a command line:
```bash
cat ~/.p4enviro
```
and see if you have a `P4CONFIG` entry

**Comment by Mashewnutz** [comment]
I'm at home but will follow up tomorrow

**Comment by Mashewnutz** [comment]
I don't have a p4enviro file setup:
cat ~/.p4enviro
cat: /Users/XXXX/.p4enviro: No such file or directory

I have this in my .bash_profile"
export P4CONFIG=.p4config

According to the docs, the value of P4CONFIG is what p4 will look for when trying to get the settings. So the name of this file could be anything, .p4config, .p4settings, .p4conf etc.

**Comment by Mashewnutz** [comment]
OK! so it seems vscode doesn't pickup values set by .bash_profile! I added .p4enviro in my home directory with this contents:

cat ~/.p4enviro
P4CONFIG=.p4config

All seems to be working now!
