### ISSUE TITLE
P4HOST and P4PORT configuration

### ISSUE THREAD

**Issue by jameelsh** [stef-levesque/vscode-perforce#81]
Hi,
the P4 plugin by default tries to connect to a server name of perforce:1666 while my server name in our company is different. How can I change the P4 server name in the plugin? I know that perforce reads it from the variables P4HOST, is it possible to configure it ?

Thanks,
Jameel

**Comment by stef-levesque** [comment]
You can create a '.p4config' or '.p4settings' file at the root of your project, with the proper P4 variables.

See https://www.perforce.com/perforce/doc.current/manuals/cmdref/P4CONFIG.html

**Comment by stef-levesque** [comment]
Otherwise, the next release of this extension will have a new setting: `perforce.port`.
I hope to publish it later this week.

**Comment by jameelsh** [comment]
.p4config worked well !! thanks !
