### ISSUE TITLE
Feature Req: connect to external perforce directory

### ISSUE THREAD

**Issue by vrachels** [stef-levesque/vscode-perforce#83]
some specs/ideas:
notify the extension to activate on a directory tree with a file, ie .p4link
contents/config in file can point to location from client  ie subPath= "folder1/folder2"
this can be appended:  p4path = PerforceService.getClientRoot() / p4link.subPath / <path from operated file to .p4link>
to get the command to p4, ie, the command line:  p4 -d <p4path> edit

use case:  source code in git, content files in perforce, all in the same vscode tree.  perforce content gets a hardlink to the actual perforce directory in its client root.  .gitignore / .p4ignore as appropriate.  Allow autocheckout, p4 ops from vscode.

**Comment by vrachels** [comment]
implemented with #88.
is anyone working on / supporting this extension?  What is the likelihood of a publish any time soon?

**Comment by stef-levesque** [comment]
Now part of version 2.2.0, please update!
