### ISSUE TITLE
Multirepo SCM support

### ISSUE THREAD

**Issue by joaomoreno** [stef-levesque/vscode-perforce#84]
With August's release, VS Code will start supporting multiple SCM providers simultaneously. This means that the user will be able to use both a Perforce repository's features alongside a git repository's features.

This new world is entirely compatible with the existing API, yet there is one small consequence. Calling `scm.createSourceControl` will create a new repository view in the SCM viewlet. This extension always calls it on activate. We suggest to change the code in order not to call `scm.createSourceControl` until a Perforce repository is actually detected in the user's workspace.

Please let us know if you need any additional information to adopt this change.

**Comment by vrachels** [comment]
fixed with #88.  still needs work to support multiple roots / p4 providers

**Comment by stef-levesque** [comment]
Now part of version 2.2.0, please update!

**Comment by joaomoreno** [comment]
Awesome!
