### ISSUE TITLE
Deploy schedule?

### ISSUE THREAD

**Issue by vrachels** [stef-levesque/vscode-perforce#90]
I've made some pull requests with some features I'd like to use and deploy to my team.

Is there any schedule for addressing the pull requests and the possibility of an updated package?

Is anyone supporting this extension?

Thanks!

**Comment by stef-levesque** [comment]
Thanks @vrachels for your contributions, it is really appreciated!

Currently my focus is on my day job. But I hope to review your PR for the week-end, and deploy a new release early next week, hopefully at the same time as VSCode release 1.16

**Comment by vrachels** [comment]
great!  Likewise - there just happens to be intersect with this plugin and my dayjob :]
Thanks for the feedback and updates!

**Comment by stef-levesque** [comment]
Thanks a lot @vrachels for the PR :+1: 
I'll test it a bit, and push a new release this week.

**Comment by stef-levesque** [comment]
Just pushed version 2.2.0, please update.
