### ISSUE TITLE
Cannot set host:port to use.

### ISSUE THREAD

**Issue by ddmendes** [stef-levesque/vscode-perforce#95]
Hi, I set the perforce.command to "p4 -u [user] -p[ip:port]" and I cannot login. But if I run "p4 -u [user] -p[ip:port] login" it works fine on cmd.

**Comment by stef-levesque** [comment]
Can you try to revert back `perforce.command` to default, and instead try the following in your user or workspace settings:

```json
{
  "perforce.user": "your_username",
  "perforce.port": "example.com:1666"
}
```
You can also set `client`, `password` or `dir`.

**Comment by stef-levesque** [comment]
hm.. it seems the latest version of the extension doesnt include that new feature... I should push a new version this week.

In the meanwhile, can you try to create a `.p4config` or `.p4settings` file at the root of your project, and add:

```
P4PORT=example.com:1666
P4CLIENT=your_client
P4USER=your_user
```

**Comment by Ben136KBC** [comment]
Thank you, this extension is awesome! I find that a .p4config or .p4settings file has no effect in my situation (using version 2.1.1 of the extension), but I can set "perforce.client" in the general settings, which works fine. However, I have a number of clients, so it would be nice to not have to set this in the general settings. Where does it look for these files? In the folder you opened (which is where I put them), or the .vscode  folder under that folder?

**Comment by stef-levesque** [comment]
You can set `perforce.client` in workspace settings, VSCode will create a `.vscode/settings.json` file for you.

**Comment by pleprince** [comment]
Looking forward to that too. Will you add a way to specify a stream too (like $P4STREAM) ?

**Comment by ddmendes** [comment]
Thank you for helping me stef-levesque.

Creating the .p4config or .p4settings file does not worked.

I don't know how to use perforce very well. I am just working on a project that is tracked with perforce (didn't even know that p4 exists) so correct me if I am wrong: the P4CLIENT option must be the workspace name?

**Comment by stef-levesque** [comment]
@pleprince I'm not sure what you want to achieve with a P4STREAM variable. 

From my understanding, switching stream is a complex operation, and is beyond the scope of this extension (at least for now)

**Comment by stef-levesque** [comment]
@ddmendes the best thing would be to get help from your work place, and to look at the official documentation: https://www.perforce.com/perforce/r17.1/manuals/cmdref/index.html#CmdRef/P4CONFIG.html?Highlight=p4config

If you can run `p4` operation from a command line, launching `vscode` from there should make the extension just work.

**Comment by Ben136KBC** [comment]
Thank you, I love this extension and how you can configure the client and so on the workspace settings.  The only request I have is, please document this in the screen that you see for this extension in vscode? At least in my experience most people have multiple clients whose name rarely match the machine name. I had to google this to find out how to set the client.

**Comment by pleprince** [comment]
@stef-levesque, you are correct: streams are complicating things quite a bit. Let's forget about them for now.
I managed to make it work, so it's all good on my end. Thanks for your time !

**Comment by molocai** [comment]
Same issue here, I'd love to be able to configure my credentials but `perforce.user` doesn't exist in the latest version

**Comment by stef-levesque** [comment]
Now part of version 2.2.0, please update and try the new settings`perforce.client`, `perforce.user`, `perforce.port`, `perforce.password`

**Comment by pleprince** [comment]
It works great. Thank you !
