### ISSUE TITLE
perforce.annotate.user isn't showing user and date

### ISSUE THREAD

**Issue by mattyork** [stef-levesque/vscode-perforce#97]
I am on version 2.2.1

I have this in my settings.json file:
```
"perforce.annotate.user": true,
```
This is what I see when I annotate:
![image](https://user-images.githubusercontent.com/666259/30602273-f26278c0-9d18-11e7-9ee2-7f707427fc2a.png)

And this is from the perforce extension log:
```
p4.exe -c loom-dev_myork4_1 -d d:/p4/loom1/loom/loom-ui/ annotate -qcu "src/app/reducers/SchemaReducer.tsx"
```

Shouldn't the annotation also show user and date?

**Comment by stef-levesque** [comment]
Can you place your cursor over the CL number ? The user and date should display in a hover box.

**Comment by stef-levesque** [comment]
@mattyork  I'm closing this with`work as designed`. The user and date are meant to be display in a hover box in order to not be too invasive.

Please reopen the bug if you disagree, or have something to propose.
